FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

EXPOSE 3100

ENV NODE_ENV=production
ENV PORT=3100

CMD ["pnpm", "start-server"]
