services:
  app:
    build:
      context: .
      no_cache: true
    image: jili-spider:latest
    container_name: jili-spider
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - jili-spider-network
    # depends_on:
    #   - mysql

  # mysql:
  #   image: mysql:8.0
  #   container_name: jili-spider-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root123
  #     MYSQL_DATABASE: aigc
  #     MYSQL_USER: jili_spider
  #     MYSQL_PASSWORD: jili_spider123
  #   ports:
  #     - "13306:3306"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   networks:
  #     - jili-spider-network

networks:
  jili-spider-network:
    driver: bridge
