services:
  app:
    build:
      context: .
      no_cache: true
    image: game-spider:latest
    container_name: game-spider
    volumes:
      - ./config:/app/config
    restart: on-failure
    networks:
      - game-spider-network
    # depends_on:
    #   - mysql

  # mysql:
  #   image: mysql:8.0
  #   container_name: game-spider-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root123
  #     MYSQL_DATABASE: aigc
  #   ports:
  #     - "33306:3306"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   networks:
  #     - game-spider-network

networks:
  game-spider-network:
    driver: bridge
