services:
  app-1:
    build:
      context: .
      no_cache: true
    image: jili-spider-1:latest
    container_name: jili-spider-1
    volumes:
      - ./config:/app/config
      - ./config/server-1.yaml:/app/config/server.yaml
    restart: on-failure
    networks:
      - jili-spider-network
  app-2:
    build:
      context: .
      no_cache: true
    image: jili-spider-2:latest
    container_name: jili-spider-2
    volumes:
      - ./config:/app/config
      - ./config/server-2.yaml:/app/config/server.yaml
    restart: on-failure
    networks:
      - jili-spider-network
  app-3:
    build:
      context: .
      no_cache: true
    image: jili-spider-3:latest
    container_name: jili-spider-3
    volumes:
      - ./config:/app/config
      - ./config/server-3.yaml:/app/config/server.yaml
    restart: on-failure
    networks:
      - jili-spider-network
  app-4:
    build:
      context: .
      no_cache: true
    image: jili-spider-4:latest
    container_name: jili-spider-4
    volumes:
      - ./config:/app/config
      - ./config/server-4.yaml:/app/config/server.yaml
    restart: on-failure
    networks:
      - jili-spider-network

  # mysql:
  #   image: mysql:8.0
  #   container_name: jili-spider-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root123
  #     MYSQL_DATABASE: aigc
  #   ports:
  #     - "33306:3306"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   networks:
  #     - jili-spider-network

networks:
  jili-spider-network:
    driver: bridge
