// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lifeServiceProto.proto" (package "lifeServiceProto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message lifeServiceProto.LifeServiceInitInfo
 */
export interface LifeServiceInitInfo {
    /**
     * @generated from protobuf field: string userID = 1
     */
    userID: string; // Field tag 1
    /**
     * @generated from protobuf field: int64 accountID = 2
     */
    accountID: bigint; // Field tag 2
    /**
     * @generated from protobuf field: int32 gameID = 3
     */
    gameID: number; // Field tag 3
    /**
     * @generated from protobuf field: string token = 4
     */
    token: string; // Field tag 4
    /**
     * @generated from protobuf field: int32 route = 5
     */
    route: number; // Field tag 5
    /**
     * @generated from protobuf field: int32 apiID = 6
     */
    apiID: number; // Field tag 6
}
// @generated message type with reflection information, may provide speed optimized methods
class LifeServiceInitInfo$Type extends MessageType<LifeServiceInitInfo> {
    constructor() {
        super("lifeServiceProto.LifeServiceInitInfo", [
            { no: 1, name: "userID", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "accountID", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "gameID", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "route", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "apiID", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<LifeServiceInitInfo>): LifeServiceInitInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userID = "";
        message.accountID = 0n;
        message.gameID = 0;
        message.token = "";
        message.route = 0;
        message.apiID = 0;
        if (value !== undefined)
            reflectionMergePartial<LifeServiceInitInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LifeServiceInitInfo): LifeServiceInitInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string userID */ 1:
                    message.userID = reader.string();
                    break;
                case /* int64 accountID */ 2:
                    message.accountID = reader.int64().toBigInt();
                    break;
                case /* int32 gameID */ 3:
                    message.gameID = reader.int32();
                    break;
                case /* string token */ 4:
                    message.token = reader.string();
                    break;
                case /* int32 route */ 5:
                    message.route = reader.int32();
                    break;
                case /* int32 apiID */ 6:
                    message.apiID = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LifeServiceInitInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string userID = 1; */
        if (message.userID !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userID);
        /* int64 accountID = 2; */
        if (message.accountID !== 0n)
            writer.tag(2, WireType.Varint).int64(message.accountID);
        /* int32 gameID = 3; */
        if (message.gameID !== 0)
            writer.tag(3, WireType.Varint).int32(message.gameID);
        /* string token = 4; */
        if (message.token !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.token);
        /* int32 route = 5; */
        if (message.route !== 0)
            writer.tag(5, WireType.Varint).int32(message.route);
        /* int32 apiID = 6; */
        if (message.apiID !== 0)
            writer.tag(6, WireType.Varint).int32(message.apiID);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lifeServiceProto.LifeServiceInitInfo
 */
export const LifeServiceInitInfo = new LifeServiceInitInfo$Type();
