proxy:
  enable: false
  server: http://127.0.0.1:7890
db:
  type: mysql
  dsn: root:m9KxXa7j@tcp(sss.cpigame.com:3306)/aigc?charset=utf8mb4&parseTime=True&loc=Local
  dialect: ""
telegram:
  enable: false
  botToken: 7562408962:AAGYI_b79AhEjscuTBPsQ6s3U2e_SNEs8x0
  chatId: "-4923815416"
  machine: local
spiderConfig:
  autoMigrate: false
  form: huidu
  compress: 1
provider: jili
gameConfig:
  bet: 0
  isOld: true
  buyBouns:
    enable: false
    index: 0
    hasDefaultIndex: true
  extra:
    enable: false
    index: 0
    hasDefaultIndex: true
  special: false
  gameName: Hyper Burst
huiduConfig:
  coin: 100000
  key: uidList1
  maxCount: 10
  uidList0:
    - 7663607
    # - 7663633
    # - 7663690
    # - 7663706
    # - 7663732
  uidListTest:
    - 7633004
  noMoneyAccounts:
    - 1641530
  uidList1:
    - 7663104
    - 7663125
    - 7663143
    - 7663258
    - 7663277
  uidList2: []
