games:
  - full_name: "Money Coming"
    company_id: 1
    game_uid: "db249defce63610fccabfa829a405232"
  - full_name: "Fortune Gems"
    company_id: 1
    game_uid: "a990de177577a2e6a889aaac5f57b429"
  - full_name: "Fortune Gems 2"
    company_id: 1
    game_uid: "664fba4da609ee82b78820b1f570f4ad"
  - full_name: "Super Ace"
    company_id: 1
    game_uid: "bdfb23c974a2517198c5443adeea77a8"
  - full_name: "Charge Buffalo"
    company_id: 1
    game_uid: "984615c9385c42b3dad0db4a9ef89070"
  - full_name: "Golden Empire"
    company_id: 1
    game_uid: "490096198e28f770a3f85adb6ee49e0f"
  - full_name: "Super Ace Deluxe"
    company_id: 1
    game_uid: "80aad2a10ae6a95068b50160d6c78897"
  - full_name: "Fortune Gems 3"
    company_id: 1
    game_uid: "63927e939636f45e9d6d0b3717b3b1c1"
  - full_name: "Boxing King"
    company_id: 1
    game_uid: "981f5f9675002fbeaaf24c4128b938d7"
  - full_name: "Mega Ace"
    company_id: 1
    game_uid: "eba92b1d3abd5f0d37dfbe112abdf0e2"
  - full_name: "Ali Baba"
    company_id: 1
    game_uid: "cc686634b4f953754b306317799f1f39"
  - full_name: "Wild Ace"
    company_id: 1
    game_uid: "9a3b65e2ae5343df349356d548f3fc4b"
  - full_name: "Crazy Hunter"
    company_id: 1
    game_uid: "69082f28fcd46cbfd10ce7a0051f24b6"
  - full_name: "Charge Buffalo Ascent"
    company_id: 1
    game_uid: "28bc4a33c985ddce6acd92422626b76f"
  - full_name: "RomaX"
    company_id: 1
    game_uid: "e5ff8e72418fcc608d72ea21cc65fb70"
  - full_name: "Money Pot"
    company_id: 1
    game_uid: "a5acbbb7ae534d303f67cb447dc8723d"
  - full_name: "3 Coin Treasures"
    company_id: 1
    game_uid: "69c1b4586b5060eefcb45bb479f03437"
  - full_name: "Aztec Priestess"
    company_id: 1
    game_uid: "6acff19b2d911a8c695ba24371964807"
  - full_name: "Golden Bank"
    company_id: 1
    game_uid: "c3f86b78938eab1b7f34159d98796e88"
  - full_name: "Devil Fire"
    company_id: 1
    game_uid: "1b4c5865131b4967513c1ee90cba4472"
  - full_name: "Fengshen"
    company_id: 1
    game_uid: "09699fd0de13edbb6c4a194d7494640b"
  - full_name: "SevenSevenSeven"
    company_id: 1
    game_uid: "61d46add6841aad4758288d68015eca6"
  - full_name: "Golden Joker"
    company_id: 1
    game_uid: "f301fe0b22d1540b1f215d282b20c642"
  - full_name: "Poseidon"
    company_id: 1
    game_uid: "50a1bcbc2ef4a5f761e0e4d338a41699"
  - full_name: "Jungle King"
    company_id: 1
    game_uid: "4db0ec24ff55a685573c888efed47d7f"
  - full_name: "Fortune Monkey"
    company_id: 1
    game_uid: "add95fc40f1ef0d56f5716ce45a56946"
  - full_name: "Bubble Beauty"
    company_id: 1
    game_uid: "a78d2ed972aab8ba06181cc43c54a425"
  - full_name: "JILI CAISHEN"
    company_id: 1
    game_uid: "11e330c2b23f106815f3b726d04e4316"
  - full_name: "Pharaoh Treasure"
    company_id: 1
    game_uid: "c7a69ab382bd1ff0e6eb65b90a793bdd"
  - full_name: "Party Night"
    company_id: 1
    game_uid: "d505541d522aa5ca01fc5e97cfcf2116"
  - full_name: "Gold Rush"
    company_id: 1
    game_uid: "2a5d731e0fd60f52873a24ece11f2c0b"
  - full_name: "3 Lucky Piggy"
    company_id: 1
    game_uid: "e09d4c9612ea540bc0afabf76e4f9148"
  - full_name: "Super Rich"
    company_id: 1
    game_uid: "b92f491a63ac84b106b056e9d46d35c5"
  - full_name: "Night City"
    company_id: 1
    game_uid: "78e29705f7c6084114f46a0aeeea1372"
  - full_name: "Secret Treasure"
    company_id: 1
    game_uid: "1d1f267e3a078ade8e5ccd56582ac94f"
  - full_name: "Golden Temple"
    company_id: 1
    game_uid: "976c5497256c020ac012005f6bb166ad"
  - full_name: "Pirate Queen"
    company_id: 1
    game_uid: "70999d5bcf2a1d1f1fb8c82e357317f4"
  - full_name: "FortunePig"
    company_id: 1
    game_uid: "8488c76ee2afb8077fbd7eec62721215"
  - full_name: "Lucky Coming"
    company_id: 1
    game_uid: "ba858ec8e3b5e2b4da0d16b3a2330ca7"
  - full_name: "Dragon Treasure"
    company_id: 1
    game_uid: "c6955c14f6c28a6c2a0c28274fec7520"
  - full_name: "Fa Fa Fa"
    company_id: 1
    game_uid: "54c41adcf43fdb6d385e38bc09cd77ca"
  - full_name: "Mayan Empire"
    company_id: 1
    game_uid: "5c2383ef253f9c36dacec4b463d61622"
  - full_name: "Fortune Tree"
    company_id: 1
    game_uid: "6a7e156ceec5c581cd6b9251854fe504"
  - full_name: "Book of Gold"
    company_id: 1
    game_uid: "6b283c434fd44250d83b7c2420f164f9"
  - full_name: "3 Pot Dragons"
    company_id: 1
    game_uid: "921dce2d616e5d0577135bb2d9214946"
  - full_name: "Hot Chilli"
    company_id: 1
    game_uid: "c845960c81d27d7880a636424e53964d"
  - full_name: "Bonus Hunter"
    company_id: 1
    game_uid: "39775cdc4170e56c5f768bdee8b4fa00"
  - full_name: "War Of Dragons"
    company_id: 1
    game_uid: "4b1d7ffaf9f66e6152ea93a6d0e4215b"
  - full_name: "Bangla Beauty"
    company_id: 1
    game_uid: "6b60d159f0939a45f7b4c88a9b57499a"
  - full_name: "God Of Martial"
    company_id: 1
    game_uid: "21ef8a7ddd39836979170a2e7584e333"
  - full_name: "Lucky Goldbricks"
    company_id: 1
    game_uid: "d84ef530121953240116e3b2e93f6af4"
  - full_name: "Sweet Land"
    company_id: 1
    game_uid: "91250a55f75a3c67ed134b99bf587225"
  - full_name: "Cricket King 18"
    company_id: 1
    game_uid: "dcf220f4e3ecca0278911a55e6f11c77"
  - full_name: "Neko Fortune"
    company_id: 1
    game_uid: "9a391758f755cb30ff973e08b2df6089"
  - full_name: "Crazy FaFaFa"
    company_id: 1
    game_uid: "a57a8d5176b54d4c825bd1eee8ab34df"
  - full_name: "Crazy777"
    company_id: 1
    game_uid: "8c62471fd4e28c084a61811a3958f7a1"
  - full_name: "Chin Shi Huang"
    company_id: 1
    game_uid: "24da72b49b0dd0e5cbef9579d09d8981"
  - full_name: "Gem Party"
    company_id: 1
    game_uid: "756cf3c73a323b4bfec8d14864e3fada"
  - full_name: "Lucky Ball"
    company_id: 1
    game_uid: "893669898cd25d9da589a384f1d004df"
  - full_name: "Hyper Burst"
    company_id: 1
    game_uid: "a47b17970036b37c1347484cf6956920"
  - full_name: "Shanghai Beauty"
    company_id: 1
    game_uid: "795d0cae623cbf34d7f1aa93bbcded28"
  - full_name: "Candy Baby"
    company_id: 1
    game_uid: "2cc3b68cbcfacac2f7ef2fe19abc3c22"
  - full_name: "Hawaii Beauty"
    company_id: 1
    game_uid: "6409b758471b6df30c6b137b49f4d92e"
  - full_name: "Bao boon chin"
    company_id: 1
    game_uid: "8c4ebb3dc5dcf7b7fe6a26d5aadd2c3d"
  - full_name: "XiYangYang"
    company_id: 1
    game_uid: "5a962d0e31e0d4c0798db5f331327e4f"
  - full_name: "DiamondParty"
    company_id: 1
    game_uid: "48d598e922e8c60643218ccda302af08"
  - full_name: "Golden Queen"
    company_id: 1
    game_uid: "8de99455c2f23f6827666fd798eb80ef"
  - full_name: "Monkey Party"
    company_id: 1
    game_uid: "fd369a4a7486ff303beea267ec5c8eff"
  - full_name: "Magic Lamp"
    company_id: 1
    game_uid: "582a58791928760c28ec4cef3392a49f"
  - full_name: "Agent Ace"
    company_id: 1
    game_uid: "8a4b4929e796fda657a2d38264346509"
  - full_name: "TWIN WINS"
    company_id: 1
    game_uid: "c74b3cbda5d16f77523e41c25104e602"
  - full_name: "Medusa"
    company_id: 1
    game_uid: "2c17b7c4e2ce5b8bebf4bd10e3e958d7"
  - full_name: "Thor X"
    company_id: 1
    game_uid: "7e6aa773fa802aaa9cb1f2fac464736e"
  - full_name: "Happy Taxi"
    company_id: 1
    game_uid: "1ed896aae4bdc78c984021307b1dd177"
  - full_name: "Crazy Pusher"
    company_id: 1
    game_uid: "00d92d5cec10cf85623938222a6c2bb6"
  - full_name: "Bone Fortune"
    company_id: 1
    game_uid: "aab3048abc6a88e0759679fbe26e6a8d"
  - full_name: "World Cup"
    company_id: 1
    game_uid: "28374b7ad7c91838a46404f1df046e5a"
  - full_name: "Samba"
    company_id: 1
    game_uid: "6d35789b2f419c1db3926350d57c58d8"
  - full_name: "Wild Racer"
    company_id: 1
    game_uid: "2f0c5f96cda3c6e16b3929dd6103df8e"
  - full_name: "Master Tiger"
    company_id: 1
    game_uid: "d2b48fe98ac2956eeefd2bc4f7e0335a"
  - full_name: "Elf Bingo"
    company_id: 1
    game_uid: "5cec2b309a8845b38f8e9b4e6d649ea2"
  - full_name: "Cricket Sah 75"
    company_id: 1
    game_uid: "6720a0ce1d06648ff390fbea832798a9"
  - full_name: "Dabanggg"
    company_id: 1
    game_uid: "5404a45b06826911c3537fdf935c281f"
  - full_name: "Sin City"
    company_id: 1
    game_uid: "830cac2f5da6cc1fb91cfae04b85b1e2"
  - full_name: "King Arthur"
    company_id: 1
    game_uid: "fafab1a17a237d0fc0e50c20d2c2bf4c"
  - full_name: "Witches Night"
    company_id: 1
    game_uid: "82c5c404cf4c0790deb42a2b5653533c"
  - full_name: "Nightfall Hunting"
    company_id: 1
    game_uid: "ced5e3de03293fc6fb111298a504cfeb"
  - full_name: "Shōgun"
    company_id: 1
    game_uid: "68724804a3cd30c749e460256b462f00"
  - full_name: "Devil Fire 2"
    company_id: 1
    game_uid: "0426ba674c9dd29de6fa023afcf0640d"
  - full_name: "Legacy of Egypt"
    company_id: 1
    game_uid: "1310248a5eab24b4bf113a6e0ee7962a"
  - full_name: "Lucky Jaguar"
    company_id: 1
    game_uid: "731e642b1fee94725e7313f3dfba8f45"
  - full_name: "Jackpot Joker"
    company_id: 1
    game_uid: "7ed860eef313538545ff7aa2b9290cf9"
  - full_name: "Arena Fighter"
    company_id: 1
    game_uid: "71468f38b1fa17379231d50635990c31"
  - full_name: "Trial of Phoenix"
    company_id: 1
    game_uid: "d11ea63b63ec615ae6df589f0b0d53e1"
  - full_name: "Zeus"
    company_id: 1
    game_uid: "4e7c9f4fbe9b5137f21ebd485a9cfa5c"
  - full_name: "Potion Wizard"
    company_id: 1
    game_uid: "fba154365cdf8fad07565cf93bae3521"
  - full_name: "Money Coming Expand Bets"
    company_id: 1
    game_uid: "3a557646c3abb12201c0b8810a8c0966"
  - full_name: "Party Star"
    company_id: 1
    game_uid: "bfde2986a4eb3a5a559ac8a8c64df461"
  - full_name: "Egypt's Glow"
    company_id: 1
    game_uid: "ddac017cb273a590b7aa0e1ad6a52bef"
  - full_name: "Golden Bank 2"
    company_id: 1
    game_uid: "3a72a27c8851be5a396f51a19654c7c3"
  - full_name: "Fruity Wheel"
    company_id: 1
    game_uid: "921cf987632d65b5e41ab5dffe16d95a"
  - full_name: "Treasure Quest"
    company_id: 1
    game_uid: "6bb74b0a57a66850b79ab5c93864cac3"
  - full_name: "Coin Tree"
    company_id: 1
    game_uid: "ca72a7ad1ca4fa2cdc9a1c49c8bb3332"
  - full_name: "Super Ace Joker"
    company_id: 1
    game_uid: "29c66f73e3916b8eb18c2bf78886927d"
  - full_name: "Pirate Queen 2"
    company_id: 1
    game_uid: "4702eb871271aa62ef3f3d78f5d968c1"
  - full_name: "Roma X Deluxe"
    company_id: 1
    game_uid: "b4fe8cea772a7643551a12de806472e8"
  - full_name: "3 LUCKY LION"
    company_id: 1
    game_uid: "7af6be9d29bb593fa0f6516b14b02103"
  - full_name: "Fortune Coins"
    company_id: 1
    game_uid: "d6d14943efe13dd3bcf1428d0f702024"
  - full_name: "Golden Empire 2"
    company_id: 1
    game_uid: "8cbb88bc0bc1f7be4379cf75abc6095f"
  - full_name: "Super Ace 2"
    company_id: 1
    game_uid: "083a2fbb35612d3f7925acedece5904f"
  - full_name: "Money Coming 2"
    company_id: 1
    game_uid: "b4a3e54cabeecd94ebbd1cc217a5b069"
  - full_name: "Circus Joker 4096"
    company_id: 1
    game_uid: "1ab23c1fda76ec10778b458fac552e37"
  - full_name: "Bikini Lady"
    company_id: 1
    game_uid: "702565a827764d10e470a0f76398a978"
