protos:
  # - name: cz72
  #   gi: 504
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mcp
  #   gi: 302
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mcp2
  #   gi: 543
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cj
  #   gi: 518
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: sss
  #   gi: 27
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: wa
  #   gi: 181
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mw4
  #   gi: 134
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ifff
  #   gi: 134
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: sr
  #   gi: 100
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: mp2
  #   gi: 303
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: ge
  #   gi: 137
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: ed
  #   gi: 324
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: df
  #   gi: 193
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ap
  #   gi: 209
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ali
  #   gi: 110
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: loe
  #   gi: 180
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bog
  #   gi: 87
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ap
  #   gi: 209
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  - name: bfs2
    gi: 259
    spin_pb_name: SpinAck
    game_info_pb_name: GameInfoData
  # - name: mpt
  #   gi: 379
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: luckytree
  #   gi: 6
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
