protos:
  # - name: cz72
  #   gi: 504
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mcp
  #   gi: 302
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mcp2
  #   gi: 543
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cj
  #   gi: 518
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: sss
  #   gi: 27
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: wa
  #   gi: 181
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mw4
  #   gi: 134
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ifff
  #   gi: 134
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: sr
  #   gi: 100
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: mp2
  #   gi: 303
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: ge
  #   gi: 137
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: ed
  #   gi: 324
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: df
  #   gi: 193
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ap
  #   gi: 209
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ali
  #   gi: 110
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: loe
  #   gi: 180
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bog
  #   gi: 87
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ap
  #   gi: 209
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bfs2
  #   gi: 259
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: mpt
  #   gi: 379
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: luckytree
  #   gi: 6
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: dl
  #   gi: 258
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: ge2
  #   gi: 424
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: rxmw
  #   gi: 517
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ctk
  #   gi: 225
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: zeus
  #   gi: 252
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: mw
  #   gi: 85
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: saj
  #   gi: 409
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: gq
  #   gi: 58
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cbt2
  #   gi: 378
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: psd
  #   gi: 375
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: pirate
  #   gi: 164
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: pirate2
  #   gi: 461
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bh
  #   gi: 142
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: c7d
  #   gi: 447
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: rg7
  #   gi: 448
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cashcoin
  #   gi: 583
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: rc
  #   gi: 523
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: sl
  #   gi: 198
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  #   gi: 136
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: cny
  #   gi: 176
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: dotd
  #   gi: 126
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bbc
  #   gi: 171
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: sweetheart
  #   gi: 17
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: sc
  #   gi: 171
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: samba
  #   gi: 136
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: mw3
  #   gi: 108
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: rg7
  #   gi: 448
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: ln
  #   gi: 145
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: eg
  #   gi: 264
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: ps
  #   gi: 240
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: csh
  #   gi: 2
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: utaxi
  #   gi: 166
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: tsq
  #   gi: 307
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: phoenix
  #   gi: 208
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: witch
  #   gi: 226
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: samurai
  #   gi: 376
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: fs
  #   gi: 38
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: sweetheart5
  #   gi: 37
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: ols
  #   gi: 21
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: chilli
  #   gi: 5
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: bby
  #   gi: 238
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: ols3
  #   gi: 40
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: fs
  #   gi: 38
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: pp
  #   gi: 33
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: tks
  #   gi: 4
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: mpt
  #   gi: 379
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: rc
  #   gi: 523
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: rc2
  #   gi: 573
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: bkex
  #   gi: 495
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: mpt2
  #   gi: 541
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: aa
  #   gi: 115
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: bikini
  #   gi: 423
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: pw
  #   gi: 299
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cnt
  #   gi: 392
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: ka
  #   gi: 214
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: dbg
  #   gi: 239
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: lj
  #   gi: 421
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GemInfo
  # - name: twinwins
  #   gi: 106
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: taxi
  #   gi: 116
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: fb
  #   gi: 146
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: cts
  #   gi: 230
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: starburst
  #   gi: 14
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: bite
  #   gi: 393
  #   spin_pb_name: SpinAck
  #   game_info_pb_name:
  # - name: fullhouse6
  #   gi: 549
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: mp
  #   gi: 67
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoAck
  # - name: tcb
  #   gi: 460
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: luckygoldbricks
  #   gi: 48
  #   spin_pb_name: AllPlate
  #   game_info_pb_name:
  # - name: dts
  #   gi: 372
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  # - name: cc
  #   gi: 485
  #   spin_pb_name: SpinAck
  #   game_info_pb_name: GameInfoData
  - name: fg4
    gi: 540
    spin_pb_name: SpinAck
    game_info_pb_name: GameInfoData
